<?php

namespace DynamicReturnTypePluginTestEnvironment\TestClasses;



class FileList extends \ArrayObject{
    const CLASS_NAME = __CLASS__;


    /**
     * @param mixed $index
     * @return \SplFileInfo
     */
    public function offsetGet( $index ) {
        return parent::offsetGet( $index ); // TODO: Change the autogenerated stub
    }


}